# Generated by Django 5.0.6 on 2024-07-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=12)),
                ('dob', models.CharField(max_length=50)),
                ('membership_plan', models.CharField(max_length=200)),
                ('trainer', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('enroll_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('phone_no', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=25)),
                ('salary', models.IntegerField(max_length=10)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
