# Generated by Django 5.0.6 on 2024-07-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_enrollment_end_date_enrollment_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
