# Generated by Django 5.0.6 on 2024-07-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_enrollment_end_date_alter_membershipplan_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
