# Generated by Django 5.0.6 on 2024-07-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_enrollment_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enroll_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
