# Generated by Django 5.0.6 on 2024-08-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_enrollment_enroll_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='duration',
            field=models.CharField(default=50, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='offer',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
