# Generated by Django 5.0.6 on 2024-08-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_membershipplan_duration_membershipplan_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
