# Generated by Django 5.0.6 on 2024-08-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_trainer_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
