# Generated by Django 5.0.6 on 2024-08-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_trainer_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='join_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
